package com.electrahub.subscription.domain;

public enum AuditAction {
    PLAN_CREATED,
    PLAN_UPDATED,
    ALLOCATION_CREATED,
    ALLOCATION_GRANTED,
    ALLOCATION_STATUS_CHANGED,
    DRIVER_SUBSCRIBED,
    ALLOCATION_PAUSED,
    ALLOCATION_REVOKED,
    UTILIZATION_PREVIEWED,
    UTILIZATION_DUPLICATE_IGNORED,
    UTILIZATION_RECORDED
}
