package com.electrahub.subscription.api.dto;

import com.electrahub.subscription.domain.AllocationStatus;
import com.electrahub.subscription.domain.AllocationSource;
import com.electrahub.subscription.domain.AllocationType;
import com.electrahub.subscription.domain.BenefitDisplayMode;
import com.electrahub.subscription.domain.PricingModel;
import com.electrahub.subscription.domain.QuotaUnit;
import com.electrahub.subscription.domain.AutoApplyPolicy;
import com.electrahub.subscription.domain.BeneficiaryType;
import com.electrahub.subscription.domain.ChargingScopeType;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;

public record SubscriptionAllocationResponse(
        UUID id,
        UUID planId,
        String planCode,
        String planName,
        String currencyCode,
        AllocationType allocationType,
        UUID userId,
        UUID organizationId,
        UUID groupId,
        Integer quotaLimit,
        BigDecimal quotaLimitValue,
        Integer effectiveQuotaLimit,
        BigDecimal effectiveQuotaLimitValue,
        int consumedUnits,
        BigDecimal consumedValue,
        Integer remainingQuota,
        BigDecimal remainingValue,
        QuotaUnit quotaUnit,
        PricingModel pricingModel,
        BenefitDisplayMode benefitDisplayMode,
        OffsetDateTime startsAt,
        OffsetDateTime endsAt,
        AllocationStatus status,
        String createdBy,
        AllocationSource source,
        String sourceLabel,
        String grantReason,
        String externalReference,
        String vin,
        UUID enterpriseId,
        BeneficiaryType beneficiaryType,
        String beneficiaryReference,
        ChargingScopeType chargingScopeType,
        String chargingScopeReference,
        AutoApplyPolicy autoApplyPolicy,
        String lastUsedChargerId,
        String lastUsedLocationId,
        String lastUsedNetworkId,
        OffsetDateTime lastUsedAt,
        OffsetDateTime createdAt,
        OffsetDateTime updatedAt
) {
}
